name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: react-prod
        run: |
          npm install
          npm run build
        working-directory: ./client
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "playground-prod"
          heroku_email: "rojasleon.dev@gmail.com"
          branch: main
        env:
          HD_MONGO_URI: ${{secrets.MONGO_URI}}
          HD_REDIS_URL: ${{secrets.REDIS_URL}}
